version: '3.2'
services:
  postgres:
    image: "postgres:9.5"
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  pgadmin4:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    links:
      - postgres:postgres
    environment:
      POSTGRES_USER: pgtest
      POSTGRES_PASSWORD: password
  redis:
    image: "grokzen/redis-cluster:latest"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "7007:7007"